### PR TITLE
[WIP] Bump `cargo-lock` dependency to v10.0.0-pre.0

### PR DESCRIPTION
**Pull request by tarcieri**

### CODE REVIEW

**Comment by tarcieri** [comment]
@Shnatsel if you can kick out an `auditable-serde` prerelease which incorporates this, we can get a `cargo-audit` prerelease out which builds on Rust 1.80

**Comment by Shnatsel** [comment]
I think I'm just going to drop the dependency on cargo-lock instead so that we never have to deal with this complex lock-step release process again. https://github.com/rust-secure-code/cargo-auditable/pull/160

**Comment by tarcieri** [comment]
Sounds good

**Comment by Shnatsel** [comment]
Closing in favor of  #160

**Pull request closed without merging**
