### PR TITLE
Add support for Rust 2024 edition

### LINKED ISSUE #170: Support for 2024 edition
I'm trying to switch to Rust 2024 Edition early to work around this problem:

https://brooksblog.bearblog.dev/rusts-sneaky-deadlock-with-if-let-blocks/

Right now cargo-auditable does not support this yet:

```
thread 'main' panicked at cargo-auditable/src/collect_audit_data.rs:87:36:
failed to parse cargo metadata output: Json(Error("unknown variant `2024`, expected one of `2015`, `2018`, `2021`", line: 1, column: 367319))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Let me know if there's anything I can do.

Thanks! :)

### PR DESCRIPTION
**Pull request by kpcyrd**
As far as I can tell this fixes #170 :)

### CODE REVIEW

**Comment by Shnatsel** [comment]
This seems like a good starting point. 

But I don't want to bump semver for all crates every time we need to upgrade `cargo_metadata`, so I'll either split the generation into its own crate or move it into `cargo-auditable` directly.

**Comment by kpcyrd** [comment]
Thanks! I'm not sure if it's too late to get this into the upcoming Alpine 3.21, but if you release a new version of cargo-auditable I'd try. :)

**Comment by Shnatsel** [comment]
I'll try to get a release out later today.

**Comment by Shnatsel** [comment]
I've published v0.6.5 with the fix.

It required changes to two underlying crates as well. If that's difficult to get packaged at this stage, you can simply apply the patch in this PR (changing 0.15 to 0.18) on the distro level.

**Comment by kpcyrd** [comment]
Thank you :black_heart: 

https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/75004

**Pull request merged**
